<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
    <Content Include="Cleanups/**/*">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    </ItemGroup>
    <ItemGroup>
      <Folder Include="Cleanups\00_OOSC_WithRemaining_BadDockets\scripts\" />
      <Folder Include="Cleanups\01_GroceryStoreRun\scripts\" />
      <Folder Include="Cleanups\03_DocketsWithoutStatusChanges\scripts\" />
      <Folder Include="Cleanups\04b_Current_Inmates_With_Status_Changes_DocketsOnly\scripts\" />
      <Folder Include="Cleanups\04_Current_Inmates_StatusChanges_With_NoHumanAction\scripts\" />
      <Folder Include="Cleanups\04_Manual_TechnicalReview\scripts\" />
      <Folder Include="Cleanups\05_Current_Inmates_StatusChanges_With_NoHumanAction\scripts\" />
      <Folder Include="Cleanups\05_Manual_TechnicalReview\scripts\" />
      <Folder Include="Cleanups\06_Current_Inmates_With_Status_Changes_DocketsOnly\scripts\" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="ClosedXML" Version="0.105.1" />
      <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.26.301" />
    </ItemGroup>
</Project>
