INSERT INTO JISJDW.AUDIT_TRAIL (AUDIT_TRAIL_ID, CJIS_SPN, CJIS_CASE_NUMBER, ACTIVITY_TABLE_NAME, ACTIVITY_USER_ID, ACTIVITY_DATE_TIME, ACTIVITY_TYPE, ACTIVITY_KEY, ACTIVITY_DETAILS) VALUES (324446797, 250159, '2026CF1214A1', 'CHARGE', 'WARRINGTONC', TIMESTAMP '2026-09-24 16:52:30', 'UPD', '1244571', ' 
CHARGE_LITERAL - old:BATTERY ON LAW ENFORCEMENT OFFICER new:VOP/BATTERY ON LAW ENFORCEMENT OFFICER
LOCATION - old:RLSD new:WARR
REOPEN_DATE - Old: NULL New:09/24/2026 12:00:00 AM
REOPEN_REASON - Old: NULL New:V
STATUS - old:R new:W
CASH_BOND_ONLY - Old: NULL New:N
ROR_INDICATOR - Old: NULL New:N
NO_BOND_IND - Old: NULL New:Y
VOP_IND - old:N new:Y
SENTENCE_CHARGE_LITERAL - old:BATTERY ON LAW ENFORCEMENT OFFICER new:VOP/BATTERY ON LAW ENFORCEMENT OFFICER');
